const path = require('path');
const express = require('express');
const boardController = require('../../controllers/dashboard');
const router = express.Router();
router.get('/', boardController.getAll);
router.get('/:dashboardId', boardController.getById);
router.post('/', boardController.addNew);
router.put('/:dashboardId', boardController.updateById);
router.delete('/:dashboarddId', boardController.removeById);
module.exports = router;
